-- ============================================================
-- AGENT DAILY SALARY CRON JOB
-- Run all of this once in Supabase SQL Editor to set up.
-- ============================================================


-- ── STEP 1: Add required columns to public.users ────────────

alter table public.users
  add column if not exists is_agent          boolean      default false,
  add column if not exists agent_id          uuid         references public.users(id),
  add column if not exists main_balance      numeric(15,2) default 0,
  add column if not exists total_bets        numeric(15,2) default 0,
  add column if not exists manual_verification boolean     default false;


-- ── STEP 2: deposits table (source of team deposit sums) ────

create table if not exists public.deposits (
  id         bigint generated by default as identity primary key,
  user_id    uuid        not null references public.users(id) on delete cascade,
  amount     numeric(15,2) not null check (amount > 0),
  created_at timestamptz default now()
);

create index if not exists idx_deposits_user_id    on public.deposits(user_id);
create index if not exists idx_deposits_created_at on public.deposits(created_at desc);


-- ── STEP 3: tasks table (daily task completion tracking) ────

create table if not exists public.tasks (
  id           bigint generated by default as identity primary key,
  user_id      uuid        not null references public.users(id) on delete cascade,
  task_date    date        not null default current_date,
  is_completed boolean     not null default false,
  unique (user_id, task_date)
);

create index if not exists idx_tasks_user_date on public.tasks(user_id, task_date);


-- ── STEP 4: salary log table (audit trail) ──────────────────

create table if not exists public.agent_salary_log (
  id                  bigint generated by default as identity primary key,
  agent_id            uuid          not null references public.users(id) on delete cascade,
  salary_date         date          not null default current_date,
  team_deposit_total  numeric(15,2) not null,
  salary_amount       numeric(15,2) not null,
  status              text          not null check (status in ('paid', 'held_manual_verification')),
  processed_at        timestamptz   default now()
);


-- ── STEP 5: The salary function ─────────────────────────────

create or replace function public.process_agent_daily_salary()
returns void
language plpgsql
security definer
as $$
declare
  rec             record;
  team_deposits   numeric(15,2);
  salary          numeric(15,2);
  task_done       boolean;
  salary_date     date := current_date - interval '1 day'; -- yesterday's deposits
begin

  -- Loop over every active agent
  for rec in
    select id
    from public.users
    where is_agent = true
  loop

    -- 1. Sum all deposits made yesterday by direct subordinates
    --    (users whose referred_by = this agent's id)
    select coalesce(sum(d.amount), 0)
    into   team_deposits
    from   public.deposits d
    join   public.users    u on u.id = d.user_id
    where  u.referred_by = rec.id
      and  d.created_at >= salary_date
      and  d.created_at <  salary_date + interval '1 day';

    salary := round(team_deposits * 0.07, 2);

    -- 2. Check if agent completed their daily task for yesterday
    select coalesce(bool_or(is_completed), false)
    into   task_done
    from   public.tasks
    where  user_id   = rec.id
      and  task_date = salary_date;

    if task_done then
      -- Release salary: add to main_balance
      update public.users
      set    main_balance = main_balance + salary,
             updated_at   = now()
      where  id = rec.id;

      insert into public.agent_salary_log
        (agent_id, salary_date, team_deposit_total, salary_amount, status)
      values
        (rec.id, salary_date, team_deposits, salary, 'paid');

    else
      -- Flag for manual verification, do NOT release salary
      update public.users
      set    manual_verification = true,
             updated_at          = now()
      where  id = rec.id;

      insert into public.agent_salary_log
        (agent_id, salary_date, team_deposit_total, salary_amount, status)
      values
        (rec.id, salary_date, team_deposits, salary, 'held_manual_verification');

    end if;

  end loop;

end;
$$;


-- ── STEP 6: Schedule with pg_cron (runs daily at 01:00 AM UTC) ──

-- Enable the extension if not already enabled (requires superuser / Supabase dashboard)
create extension if not exists pg_cron;

-- Remove any existing schedule with the same name to avoid duplicates
select cron.unschedule('agent_daily_salary')
where exists (
  select 1 from cron.job where jobname = 'agent_daily_salary'
);

select cron.schedule(
  'agent_daily_salary',          -- job name
  '0 1 * * *',                   -- cron expression: 01:00 AM UTC daily
  $$ select public.process_agent_daily_salary(); $$
);
