-- Supabase SQL for persistent auth and abuse audit logging.
-- Apply this in the Supabase SQL Editor.

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  phone_number text,
  ip_address text,
  device_id text,
  device_fingerprint text,
  user_agent text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.registration_attempts (
  id bigint generated by default as identity primary key,
  ip text,
  phone_number text,
  device_fingerprint text,
  device_id text,
  user_agent text,
  attempted_at timestamptz default now()
);

create index if not exists idx_security_events_created_at on public.security_events(created_at desc);
create index if not exists idx_security_events_phone on public.security_events(phone_number);
create index if not exists idx_registration_attempts_attempted_at on public.registration_attempts(attempted_at desc);
create index if not exists idx_registration_attempts_ip on public.registration_attempts(ip);
create index if not exists idx_registration_attempts_device_fingerprint on public.registration_attempts(device_fingerprint);

-- These tables are intended for backend audit logging via service-role access.
-- RLS policies are omitted here because security events and registration attempts
-- should be written/read by the server-only backend.

create policy security_events_admin_all
  on public.security_events
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy registration_attempts_admin_all
  on public.registration_attempts
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
