-- ================================================================
-- RUN THIS ENTIRE SCRIPT IN SUPABASE SQL EDITOR
-- ================================================================

-- ── 1. Fix withdraw_requests: add missing columns ────────────────
create table if not exists public.withdraw_requests (
  id             text         primary key,
  user_id        uuid         references public.users(id) on delete cascade,
  amount         numeric(15,2) not null default 0,
  bank_name      text,
  account_name   text,
  account_number text,
  status         text         not null default 'pending',
  reason         text,
  created_at     timestamptz  default now()
);
alter table public.withdraw_requests
  add column if not exists bank_name      text,
  add column if not exists account_name   text,
  add column if not exists account_number text,
  add column if not exists reason         text,
  add column if not exists status         text default 'pending';

-- ── 2. Fix gift_codes table ──────────────────────────────────────
create table if not exists public.gift_codes (
  id            uuid         primary key default gen_random_uuid(),
  code          text         not null unique,
  amount        numeric(15,2) not null default 0,
  status        text         not null default 'active',
  claimed_by    uuid         references public.users(id),
  created_at    timestamptz  default now(),
  expires_at    timestamptz,
  admin_remarks text
);
alter table public.gift_codes
  add column if not exists claimed_by    uuid references public.users(id),
  add column if not exists expires_at    timestamptz,
  add column if not exists admin_remarks text;

-- ── 3. Fix gift_code_claims table (correct schema) ───────────────
drop table if exists public.gift_code_claims cascade;
create table public.gift_code_claims (
  id         bigint generated by default as identity primary key,
  user_id    uuid        not null references public.users(id) on delete cascade,
  gift_code  text        not null,   -- the code string (not FK)
  amount     numeric(15,2) not null default 0,
  created_at timestamptz default now(),
  unique (user_id, gift_code)
);
create index if not exists idx_gift_code_claims_user on public.gift_code_claims(user_id);
create index if not exists idx_gift_code_claims_code on public.gift_code_claims(gift_code);

-- ── 4. Attendance bonus table ────────────────────────────────────
create table if not exists public.attendance_bonus (
  id              bigint generated by default as identity primary key,
  user_id         uuid        not null references public.users(id) on delete cascade,
  day_number      integer     not null,   -- 1-7
  claimed_at      timestamptz default now(),
  deposit_amount  numeric(15,2) default 0,
  reward_amount   numeric(15,2) default 0,
  unique (user_id, day_number)
);
create index if not exists idx_attendance_user on public.attendance_bonus(user_id);

-- ── 5. Add wagering_completed column to users (if missing) ───────
alter table public.users
  add column if not exists wagering_completed numeric(15,2) default 0;

-- ── 6. RLS for new tables ────────────────────────────────────────
alter table public.gift_codes        enable row level security;
alter table public.gift_code_claims  enable row level security;
alter table public.attendance_bonus  enable row level security;
alter table public.withdraw_requests enable row level security;

-- gift_codes: anyone can read active, service role manages
drop policy if exists "gc_read_active"   on public.gift_codes;
drop policy if exists "gc_service_all"   on public.gift_codes;
create policy "gc_read_active"  on public.gift_codes for select using (status = 'active' or auth.role() = 'service_role');
create policy "gc_service_all"  on public.gift_codes for all   using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- gift_code_claims: own rows
drop policy if exists "gcc_own"         on public.gift_code_claims;
drop policy if exists "gcc_service_all" on public.gift_code_claims;
create policy "gcc_own"         on public.gift_code_claims for all using (auth.uid() = user_id or auth.role() = 'service_role') with check (auth.uid() = user_id or auth.role() = 'service_role');
create policy "gcc_service_all" on public.gift_code_claims for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- attendance_bonus: own rows
drop policy if exists "ab_own"          on public.attendance_bonus;
create policy "ab_own" on public.attendance_bonus for all using (auth.uid() = user_id or auth.role() = 'service_role') with check (auth.uid() = user_id or auth.role() = 'service_role');

-- withdraw_requests: own rows
drop policy if exists "wr_select_own"   on public.withdraw_requests;
drop policy if exists "wr_insert_own"   on public.withdraw_requests;
drop policy if exists "wr_service_all"  on public.withdraw_requests;
create policy "wr_select_own"  on public.withdraw_requests for select using (auth.uid() = user_id or auth.role() = 'service_role');
create policy "wr_insert_own"  on public.withdraw_requests for insert with check (auth.uid() = user_id or auth.role() = 'service_role');
create policy "wr_service_all" on public.withdraw_requests for all   using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
