-- ================================================================
-- STEP 1: Ensure users table has all required columns
-- ================================================================
alter table public.users
  add column if not exists status              text         default 'active',
  add column if not exists total_bets          numeric(15,2) default 0,
  add column if not exists main_balance        numeric(15,2) default 0,
  add column if not exists game_balance        numeric(15,2) default 0,
  add column if not exists wagering_required   numeric(15,2) default 0,
  add column if not exists wagering_completed  numeric(15,2) default 0;

-- ================================================================
-- STEP 2: Dashboard aggregate view (fixes Overview ↔ Member count mismatch)
-- ================================================================
create or replace view public.dashboard_stats as
select
  (select count(*)                          from public.users)                                          as total_users,
  (select coalesce(sum(main_balance), 0)    from public.users)                                          as total_wallet_balance,
  (select count(*)                          from public.withdraw_requests where status = 'pending')     as pending_withdrawals,
  (select count(*)                          from public.transactions      where status = 'pending'
                                                                           and  type   = 'deposit')     as pending_deposits;

-- Allow admin (service_role) and authenticated users to read the view
grant select on public.dashboard_stats to authenticated, service_role;

-- ================================================================
-- STEP 3: Payment Gateway webhook — update balance + activate wagering
-- ================================================================
create or replace function public.handle_gateway_deposit(
  p_user_id   uuid,
  p_amount    numeric,
  p_tx_ref    text
)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_bonus        numeric;
  v_bonus_pct    numeric;
  v_new_balance  numeric;
begin
  -- Idempotency: skip if tx_ref already processed
  if exists (
    select 1 from public.transactions
    where reference = p_tx_ref and type = 'deposit' and status = 'completed'
  ) then
    return jsonb_build_object('status', 'duplicate', 'tx_ref', p_tx_ref);
  end if;

  -- Read deposit bonus % from platform_settings
  select coalesce(deposit_bonus, 0) into v_bonus_pct
  from public.platform_settings where id = 'default';

  v_bonus := round(p_amount * coalesce(v_bonus_pct, 0) / 100, 2);

  -- Credit main_balance + activate wagering
  update public.users
  set
    main_balance       = main_balance + p_amount + v_bonus,
    wagering_required  = wagering_required  + p_amount + v_bonus,
    wagering_completed = 0
  where id = p_user_id
  returning main_balance into v_new_balance;

  -- Log the transaction
  insert into public.transactions (user_id, type, amount, status, reference, created_at)
  values (p_user_id, 'deposit', p_amount, 'completed', p_tx_ref, now());

  return jsonb_build_object(
    'status',      'ok',
    'new_balance', v_new_balance,
    'bonus',       v_bonus,
    'tx_ref',      p_tx_ref
  );
end;
$$;

-- ================================================================
-- STEP 4: Smart Risk Management — flag abnormal betting patterns
-- ================================================================
create table if not exists public.risk_logs (
  id           bigint generated by default as identity primary key,
  user_id      uuid        not null references public.users(id) on delete cascade,
  period       text,
  bet_amount   numeric(15,2),
  volatility   numeric(6,4),
  flag_reason  text,
  created_at   timestamptz default now()
);
create index if not exists idx_risk_logs_user on public.risk_logs(user_id);
create index if not exists idx_risk_logs_time on public.risk_logs(created_at desc);

alter table public.risk_logs enable row level security;
create policy "risk_service_all" on public.risk_logs
  for all using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
-- Admin (authenticated) can read
create policy "risk_admin_read" on public.risk_logs
  for select using (auth.role() = 'authenticated' or auth.role() = 'service_role');

-- Function: called after every bet to detect abnormal patterns
create or replace function public.check_bet_risk(
  p_user_id   uuid,
  p_period    text,
  p_amount    numeric
)
returns void
language plpgsql
security definer
as $$
declare
  v_avg        numeric;
  v_stddev     numeric;
  v_volatility numeric;
  v_reason     text := null;
begin
  -- Compute avg + stddev of last 20 bets for this user
  select
    coalesce(avg(bet_amount), 0),
    coalesce(stddev(bet_amount), 0)
  into v_avg, v_stddev
  from (
    select bet_amount from public.risk_logs
    where user_id = p_user_id
    order by created_at desc
    limit 20
  ) recent;

  -- Volatility = coefficient of variation (stddev / avg)
  v_volatility := case when v_avg > 0 then round(v_stddev / v_avg, 4) else 0 end;

  -- Flag if: bet is > 5× the user's average OR volatility > 3.0
  if p_amount > v_avg * 5 and v_avg > 0 then
    v_reason := 'bet_spike: ' || p_amount || ' vs avg ' || round(v_avg, 2);
  elsif v_volatility > 3.0 then
    v_reason := 'high_volatility: cv=' || v_volatility;
  end if;

  -- Always log; only set flag_reason when abnormal
  insert into public.risk_logs (user_id, period, bet_amount, volatility, flag_reason)
  values (p_user_id, p_period, p_amount, v_volatility, v_reason);
end;
$$;

-- ================================================================
-- STEP 5: Ensure transactions table has a reference column
-- ================================================================
alter table public.transactions
  add column if not exists reference text,
  add column if not exists type       text default 'deposit',
  add column if not exists status     text default 'pending';

create unique index if not exists idx_transactions_ref
  on public.transactions(reference)
  where reference is not null;

-- ================================================================
-- STEP 6: platform_settings — ensure deposit_bonus column exists
-- ================================================================
alter table public.platform_settings
  add column if not exists deposit_bonus numeric(5,2) default 50;
